#11.4 규제를 사용한 과대적합 피하기

###11.4.1 $l_1$ 규제와 $l_2$ 규제

* 오버피팅(overfitting)
  * 학습 데이터에 대해서는 과도하게 학습이 되어 좋은 예측력을 보이지만, 새로운  데이터에 대해서는 예측력이 떨어지는 것

  <img src = 'https://drive.google.com/uc?export=view&id=1RItK50oeIqqRX72PkN-UmgYl6thAcp_Q' align = 'middle'>



  

* 기본 아이디어
  <img src='https://drive.google.com/uc?export=view&id=10LLxS6nD8KVJkhjBUIaUK2WuTPqL0H03' width=700>

  * parameter 갱신은 Cost function을 최소화 하는 것을 목표로 하여 진행된다.
  * 만약 cost function이  $\displaystyle\sum(y_i - \hat y_i )^2$라고 했을 때, weight가 $ \beta_1, \beta_2, \beta_3, \beta_4 $ 로 4개가 존재하고, bias가 $\beta_0$ 라고 가정해보자.
  * 현재 규제가 없는 cost function을 사용할 때 우측 그림과 같이 overfitting 되고 있다.
  * 이를 좌측 그림과 같이 더 general한 모델로 만들기 위해서는 weight들에 규제를 가해야 할 필요성이 있다.
  * 가장 극단적인 규제는 몇 개의 weight를 아예 0으로 만드는 방법이다. 
  * $min_\beta \sum(y_i - \hat y_i)^2 + 5000 \beta_3^2 + 5000 \beta_4 ^2$ 
  * $\beta_3, \beta4$에 매우 큰 수준의 규제로 5000을 곱해주었다. cost function을 최소화 하기 위해서는 $\beta_3$와 $\beta_4$가 0에 가까워져야 할 것이다.
  * 결국 우측 그림에서 좌측 그림으로 overfitting 문제가 해결되었다.
  * 위 예시는 이해를 돕기 위한 극단적인 상황을 가정한 것이고, 실제로는 저렇게 큰 수를 곱해서 weight를 완전히 죽이지는 않는다.
  * 이렇게 weight에 특정 값을 곱해서 제약을 가함으로써 overfitting을 해결하는 것이 L1, L2 규제의 기본 아이디어이다.





* norm이란?
  * $L^x = || p-q ||_x = (\sum |p_i-q_i|^x)^\frac{1}{x})$
  * 두 벡터간의 크기 또는 길이를 뜻한다.
  * x의 값에 따라 $l^1 ~~norm, l^2 ~~norm ... l^\infty$ 로 표기되고, x의 값의 범위는 1보다 크거나 같은 실수이다.
  * 벡터 x의 $norm$은 원점에서 x까지의 거리를 나타낸다.

 <img src = 'https://drive.google.com/uc?export=view&id=1Ty1yBWyC4vah1jUZVSO6VKJiqoVJpJmQ' width = 300>

  * $L^1 norm$
    * $L^1 = \displaystyle \sum_{i=1}^{n} |p-q| = |  p_1-q_1|+|p_2-q_2|+|p_3-q_3|+ ... +|p_n-q_n|$
    * 맨하탄 거리(Manhattan Distance)라고도 한다.

  * $L^2 norm$
    * $L^1 =\displaystyle(\sum_{i=1}^{n} |p-q|^2) ^\frac{1}{2} = \sqrt{(p_1-q_1)^2+(p_2-q_2)^2+( p_3-q_3)^2+ ... +(p_n-q_n)^2}$
    * 유클리디안 거리(Euclidean norm)

* L1 규제(L1 Regularization)
 <img src = 'https://drive.google.com/uc?export=view&id=1dB0P0H9MmyOnlt1oWUzAJ4AYw3tcGlP4'>

 * 앞에 붙는 $\frac{1}{n}$은 case에 따라 다르게 적용함.
 * $\lambda$의 경우 parameter로서 keras 사용시 임의의 값을 부여할 수 있음.


* L1 규제가 적용된 cost function 미분
  * L1 규제가 적용된 cost function을 더욱 간단하게 표현해 보았다. $Cost = C_0 + \frac{\lambda}{n} \sum |w|$
  * 이 식을 w에 대해 편미분하면 다음과 같다. $w → w - \frac{\eta \lambda}{n}sgn(w) - \eta \frac{\partial C_0}{\partial w}$
  * 위 식에서 weight는 전 step의 weight의 크기와 상관 없이 weight의 부호에 따라 상수 값을 빼주주는 방식으로 갱신된다.


* L2 규제(L2 Regularization)
<img src = 'https://drive.google.com/uc?export=view&id=1sTI6kLMuMfZ7-Es13jf7we46C4t7JT5Z'>

  * L2 규제가 적용된 cost function 미분
  * L2 규제가 적용된 cost function을 더욱 간단하게 표현해 보았다. $Cost = C_0 + \frac{\lambda}{2n} \sum w^2$
  * 이 식을 w에 대해 편미분 하면 다음과 같다. 
  * $w → w - \frac{\eta \lambda}{n} - \eta \frac{\partial C_0}{\partial w}$
  * = $(1 - \frac{\eta \lambda}{n})w - \eta \frac{\partial C_0}{\partial w}$
  * 위 식에서 weight는 전 setp의 weight에 $(1 - \frac{\eta \lambda}{n})$를 곱해주며 갱신된다.


* 결론 : L1 규제와 L2 규제 중 무엇을 사용해야 하는가?
  * L1 규제는 규제의 크기($\lambda$)가 커질수록 가중치가 0에 가까워지기 때문에 underfitting될 가능성이 크다.
  * 하지만, L2 규제는 규제의 크기($\lambda$)가 커져도 가중치가 0에 가까워지는 정도가 덜 하기 때문에 underfitting이 잘 되지 않는다.
  * 결론적으로는 L1 규제보다 L2 규제를 더 많이 사용한다.



In [2]:
from tensorflow.keras.datasets.fashion_mnist import load_data
from tensorflow import keras

In [3]:
(X_train, y_train), (X_test, y_test) = load_data()
X_train = X_train/255.
X_test = X_test/255.

4431872/4422102 [==============================] - 0s 0us/step


In [4]:
X_test.shape

(10000, 28, 28)

In [5]:
class_names=['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

In [6]:
layer=keras.layers.Dense(100, activation='elu', kernel_initializer='he_normal',
                         kernel_regularizer=keras.regularizers.l2(0.01))

In [7]:
#Code refactoring
from functools import partial

RegularizedDense=partial(keras.layers.Dense,
                         activation='elu',
                         kernel_initializer='he_normal',
                         kernel_regularizer=keras.regularizers.l2(0.01))

model=keras.models.Sequential([
                               keras.layers.Flatten(input_shape=[28, 28]),
                               RegularizedDense(300),
                               RegularizedDense(100),
                               RegularizedDense(10, activation='softmax', kernel_initializer='glorot_uniform')
])

##11.4.2 드롭아웃(Dropout)
 <img src = 'https://drive.google.com/uc?export=view&id=1hBxujo4dufY_B31UbTkIrtEWXzgoPiJz' width=600>

* 방법
  * 매 training step에서 각 뉴런은 임시적으로 드롭아웃 될 확률은 p이다(예를 들어 p가 0.5일 경우 전체 뉴런 중 50%의 뉴런이 해당 step 훈련에서 제외된다).
  * 드롭아웃 되는 뉴런들은 해당 step에서 훈련에서 제외된다.
  * 훈련이 끝난 후 최종 모델(test 혹은 상용화를 위한 모델)에서는 dropout을 적용하지 않고 모든 뉴런을 다 사용한다. 단, 각 뉴런은 훈련 때 드롭아웃으로 인해 더 적은 입력 뉴런과 연결되었기 때문에 훈련이 끝난 후 모든 뉴런을 다 사용할 때에는 각 가중치에 **보존확률 = (1-p)**를 곱해줘야 한다.

* 드롭 아웃이 작동하는 원리
  * Co-adaptation 방지 : 신경망 학습 중 어느 시점에서 같은 층의 두 개 이상의 뉴런의 입력 및 출력 연결 강도가 같아지만, 학습을 계속 진행해도 해당 뉴런들은 같은 일을 수행하게 되어 불필요한 중복이 생기게 된다. 드롭 아웃은 이러한 Co-adaptation을 방지하는 방식으로 신경망 성능을 높인다.
  * Ensemble : step별로 확률에 따라 뉴런들이 드롭 아웃 되면서, 더 작은 네트워크가 형성되고 그 네트워크로 훈련을 진행하게 된다. 그리고 그 다음 step엔 이전에 훈련되었던 네트워크를 반영해 뉴런을 드롭 아웃 후 다른 네트워크로 훈련을 진행한다. 결국 매 epoch마다 다른 모델을 만들고 이를 다음 epoch에 반영하여 모델을 만들기 때문에 Ensemble효과가 발생한다.

In [8]:
model_normal=keras.models.Sequential([
                               keras.layers.Flatten(input_shape=[28,28]),
                               keras.layers.Dense(300,activation='elu',kernel_initializer='he_normal'),
                               keras.layers.Dense(100,activation='elu',kernel_initializer='he_normal'),
                               keras.layers.Dense(10,activation='softmax')
])

In [9]:
model_normal.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 300)               235500    
_________________________________________________________________
dense_5 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_6 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [10]:
model_normal.compile(optimizer='adam',
                      loss='sparse_categorical_crossentropy',
                      metrics=['acc'])

In [11]:
hist_2=model_normal.fit(X_train, y_train,
                         epochs=25,
                         validation_split=0.3,
                         batch_size=128)

Epoch 1/25
329/329 [==============================] - 3s 8ms/step - loss: 0.5372 - acc: 0.8083 - val_loss: 0.4289 - val_acc: 0.8437
Epoch 2/25
329/329 [==============================] - 2s 7ms/step - loss: 0.3987 - acc: 0.8541 - val_loss: 0.4090 - val_acc: 0.8504
Epoch 3/25
329/329 [==============================] - 2s 7ms/step - loss: 0.3547 - acc: 0.8704 - val_loss: 0.3537 - val_acc: 0.8719
Epoch 4/25
329/329 [==============================] - 2s 7ms/step - loss: 0.3283 - acc: 0.8776 - val_loss: 0.3600 - val_acc: 0.8696
Epoch 5/25
329/329 [==============================] - 2s 7ms/step - loss: 0.3117 - acc: 0.8856 - val_loss: 0.3373 - val_acc: 0.8764
Epoch 6/25
329/329 [==============================] - 2s 7ms/step - loss: 0.2902 - acc: 0.8914 - val_loss: 0.3347 - val_acc: 0.8806
Epoch 7/25
329/329 [==============================] - 2s 7ms/step - loss: 0.2790 - acc: 0.8962 - val_loss: 0.4177 - val_acc: 0.8520
Epoch 8/25
329/329 [==============================] - 2s 7ms/step - loss: 0.

In [12]:
model_dropout=keras.models.Sequential([
                               keras.layers.Flatten(input_shape=[28,28]),
                               keras.layers.Dropout(rate=0.2),
                               keras.layers.Dense(300,activation='elu',kernel_initializer='he_normal'),
                               keras.layers.Dropout(rate=0.2),
                               keras.layers.Dense(100,activation='elu',kernel_initializer='he_normal'),
                               keras.layers.Dropout(rate=0.2),
                               keras.layers.Dense(10,activation='softmax')
])

In [13]:
model_dropout.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          (None, 784)               0         
_________________________________________________________________
dropout (Dropout)            (None, 784)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 300)               235500    
_________________________________________________________________
dropout_1 (Dropout)          (None, 300)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 100)               30100     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_9 (Dense)              (None, 10)               

In [14]:
model_dropout.compile(optimizer='adam',
                      loss='sparse_categorical_crossentropy',
                      metrics=['acc'])

In [15]:
hist_2=model_dropout.fit(X_train, y_train,
                         epochs=25,
                         validation_split=0.3,
                         batch_size=128)

Epoch 1/25
329/329 [==============================] - 4s 10ms/step - loss: 0.6582 - acc: 0.7615 - val_loss: 0.4571 - val_acc: 0.8347
Epoch 2/25
329/329 [==============================] - 3s 9ms/step - loss: 0.4922 - acc: 0.8202 - val_loss: 0.4034 - val_acc: 0.8502
Epoch 3/25
329/329 [==============================] - 3s 9ms/step - loss: 0.4529 - acc: 0.8318 - val_loss: 0.3804 - val_acc: 0.8602
Epoch 4/25
329/329 [==============================] - 3s 9ms/step - loss: 0.4303 - acc: 0.8392 - val_loss: 0.3797 - val_acc: 0.8603
Epoch 5/25
329/329 [==============================] - 3s 10ms/step - loss: 0.4111 - acc: 0.8461 - val_loss: 0.3599 - val_acc: 0.8687
Epoch 6/25
329/329 [==============================] - 3s 10ms/step - loss: 0.3986 - acc: 0.8511 - val_loss: 0.3472 - val_acc: 0.8732
Epoch 7/25
329/329 [==============================] - 3s 10ms/step - loss: 0.3867 - acc: 0.8557 - val_loss: 0.3458 - val_acc: 0.8719
Epoch 8/25
329/329 [==============================] - 3s 9ms/step - loss

In [16]:
model_dropout.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.3227 - acc: 0.8822


[0.32266896963119507, 0.8822000026702881]

##11.4.3 몬테 카를로 드롭아웃(Monte-Carlo Dropout)


* 일반적인 드롭아웃과는 달리, 몬테 카를로 드롭아웃을 적용하게 되면, test과정에서도 드롭아웃을 적용하고, 여러 개의 예측 결과를 통해 더욱 '불확실성'이 줄어든 예측을 할 수 있다. 

In [17]:
import numpy as np
y_probas = np.stack([model_dropout(X_test, training=True)
                     for sample in range(100)])
y_proba=y_probas.mean(axis=0)

In [18]:
#MC 드롭아웃을 적용하지 않은 예측 결과
np.round(model_dropout.predict(X_test[:1]), 2)

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.03, 0.  , 0.97]],
      dtype=float32)

In [25]:
np.round(y_probas[:,:1],2)

array([[[0.  , 0.  , 0.  , 0.  , 0.  , 0.21, 0.  , 0.07, 0.  , 0.72]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.99]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.42, 0.  , 0.53]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.95]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.01, 0.  , 0.98]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.02, 0.  , 0.97]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.  , 0.07, 0.  , 0.89]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.03, 0.  , 0.14, 0.  , 0.82]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.  , 0.89]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.08, 0.  , 0.91]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.07, 0.  , 0.25, 0.  , 0.68]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.09, 0.  , 0.9 ]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.06, 0.  , 0.07, 0.  , 0.87]],

       [[0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.08, 0.  , 0

In [20]:
#axis=0 기준으로 평균값을 구함.
np.round(y_proba[:1], 2)

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.06, 0.  , 0.08, 0.  , 0.87]],
      dtype=float32)

In [21]:
y_std=y_probas.std(axis=0)
np.round(y_std[:1], 2)

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.13, 0.  , 0.1 , 0.  , 0.17]],
      dtype=float32)

In [22]:
y_pred = np.argmax(y_proba, axis=1)

In [23]:
accuracy=np.sum(y_pred==y_test) / len(y_test)
accuracy

0.8824

##11.4.4 맥스-노름 규제(max-norm regularization)

* 각 뉴런에 대한 입력의 연결 가중치 w가 다음과 같도록 제한한다($||w||_2 \leq r$).
* 맥스-노름 규제에서는 손실 함수에 규제 항을 추가하지 않는다.
* 대신 매 훈련 스텝이 끝날 때마다 w의 norm의 계산하여 다음과 같이 스케일 조정을 시행한다. $w ← w \frac{r}{||w||_2}$ 
*r은 하이퍼 파라미터로서 조절 가능하며, r을 줄이면 w에 더 작은 값이 곱해지기 때문에 가중치가 더욱 작아지게 되고 overfitting을 감소시키는데 도움이 된다.

In [24]:
keras.layers.Dense(100, activation='elu', kernel_initializer='he_normal',
                   kernel_constraint=keras.constraints.max_norm(1.))